/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as PortalPropostasRouteImport } from './routes/portal.propostas'
import { Route as PortalOsRouteImport } from './routes/portal.os'
import { Route as PortalFinanceiroRouteImport } from './routes/portal.financeiro'
import { Route as PortalDocumentosRouteImport } from './routes/portal.documentos'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as CesTokenRouteImport } from './routes/ces.$token'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated.leads'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated.compliance'
import { Route as AuthenticatedBiRouteImport } from './routes/_authenticated.bi'
import { Route as AuthenticatedPropostasIndexRouteImport } from './routes/_authenticated.propostas.index'
import { Route as AuthenticatedOsIndexRouteImport } from './routes/_authenticated.os.index'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated.financeiro.index'
import { Route as AuthenticatedComplianceIndexRouteImport } from './routes/_authenticated.compliance.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated.clientes.index'
import { Route as AuthenticatedBiIndexRouteImport } from './routes/_authenticated.bi.index'
import { Route as AuthenticatedPropostasIdRouteImport } from './routes/_authenticated.propostas.$id'
import { Route as AuthenticatedOsIdRouteImport } from './routes/_authenticated.os.$id'
import { Route as AuthenticatedFinanceiroReceberRouteImport } from './routes/_authenticated.financeiro.receber'
import { Route as AuthenticatedFinanceiroPagarRouteImport } from './routes/_authenticated.financeiro.pagar'
import { Route as AuthenticatedDiagnosticosNovoRouteImport } from './routes/_authenticated.diagnosticos.novo'
import { Route as AuthenticatedComplianceRtRouteImport } from './routes/_authenticated.compliance.rt'
import { Route as AuthenticatedComplianceProdutosRegulatorioRouteImport } from './routes/_authenticated.compliance.produtos-regulatorio'
import { Route as AuthenticatedComplianceLivroAplicacoesRouteImport } from './routes/_authenticated.compliance.livro-aplicacoes'
import { Route as AuthenticatedComplianceEpisRouteImport } from './routes/_authenticated.compliance.epis'
import { Route as AuthenticatedComplianceEmbalagensRouteImport } from './routes/_authenticated.compliance.embalagens'
import { Route as AuthenticatedComplianceCertificadosRouteImport } from './routes/_authenticated.compliance.certificados'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated.clientes.$id'
import { Route as AuthenticatedCadastrosServicosRouteImport } from './routes/_authenticated.cadastros.servicos'
import { Route as AuthenticatedCadastrosProdutosRouteImport } from './routes/_authenticated.cadastros.produtos'
import { Route as AuthenticatedCadastrosEquipesRouteImport } from './routes/_authenticated.cadastros.equipes'
import { Route as AuthenticatedCadastrosEpisRouteImport } from './routes/_authenticated.cadastros.epis'
import { Route as AuthenticatedCadastrosCategoriasFinanceirasRouteImport } from './routes/_authenticated.cadastros.categorias-financeiras'
import { Route as AuthenticatedBiOperacionalRouteImport } from './routes/_authenticated.bi.operacional'
import { Route as AuthenticatedBiFinanceiroRouteImport } from './routes/_authenticated.bi.financeiro'
import { Route as AuthenticatedBiEstoqueRouteImport } from './routes/_authenticated.bi.estoque'
import { Route as AuthenticatedBiComercialRouteImport } from './routes/_authenticated.bi.comercial'
import { Route as AuthenticatedFinanceiroReceberIdRouteImport } from './routes/_authenticated.financeiro.receber.$id'
import { Route as AuthenticatedFinanceiroPagarIdRouteImport } from './routes/_authenticated.financeiro.pagar.$id'
import { Route as AuthenticatedFinanceiroLancamentoNovoRouteImport } from './routes/_authenticated.financeiro.lancamento.novo'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PortalPropostasRoute = PortalPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOsRoute = PortalOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFinanceiroRoute = PortalFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentosRoute = PortalDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => PortalRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CesTokenRoute = CesTokenRouteImport.update({
  id: '/ces/$token',
  path: '/ces/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBiRoute = AuthenticatedBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropostasIndexRoute =
  AuthenticatedPropostasIndexRouteImport.update({
    id: '/propostas/',
    path: '/propostas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOsIndexRoute = AuthenticatedOsIndexRouteImport.update({
  id: '/os/',
  path: '/os/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/financeiro/',
    path: '/financeiro/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceIndexRoute =
  AuthenticatedComplianceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComplianceRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBiIndexRoute = AuthenticatedBiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedBiRoute,
} as any)
const AuthenticatedPropostasIdRoute =
  AuthenticatedPropostasIdRouteImport.update({
    id: '/propostas/$id',
    path: '/propostas/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOsIdRoute = AuthenticatedOsIdRouteImport.update({
  id: '/os/$id',
  path: '/os/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroReceberRoute =
  AuthenticatedFinanceiroReceberRouteImport.update({
    id: '/financeiro/receber',
    path: '/financeiro/receber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroPagarRoute =
  AuthenticatedFinanceiroPagarRouteImport.update({
    id: '/financeiro/pagar',
    path: '/financeiro/pagar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiagnosticosNovoRoute =
  AuthenticatedDiagnosticosNovoRouteImport.update({
    id: '/diagnosticos/novo',
    path: '/diagnosticos/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceRtRoute =
  AuthenticatedComplianceRtRouteImport.update({
    id: '/rt',
    path: '/rt',
    getParentRoute: () => AuthenticatedComplianceRoute,
  } as any)
const AuthenticatedComplianceProdutosRegulatorioRoute =
  AuthenticatedComplianceProdutosRegulatorioRouteImport.update({
    id: '/produtos-regulatorio',
    path: '/produtos-regulatorio',
    getParentRoute: () => AuthenticatedComplianceRoute,
  } as any)
const AuthenticatedComplianceLivroAplicacoesRoute =
  AuthenticatedComplianceLivroAplicacoesRouteImport.update({
    id: '/livro-aplicacoes',
    path: '/livro-aplicacoes',
    getParentRoute: () => AuthenticatedComplianceRoute,
  } as any)
const AuthenticatedComplianceEpisRoute =
  AuthenticatedComplianceEpisRouteImport.update({
    id: '/epis',
    path: '/epis',
    getParentRoute: () => AuthenticatedComplianceRoute,
  } as any)
const AuthenticatedComplianceEmbalagensRoute =
  AuthenticatedComplianceEmbalagensRouteImport.update({
    id: '/embalagens',
    path: '/embalagens',
    getParentRoute: () => AuthenticatedComplianceRoute,
  } as any)
const AuthenticatedComplianceCertificadosRoute =
  AuthenticatedComplianceCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedComplianceRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCadastrosServicosRoute =
  AuthenticatedCadastrosServicosRouteImport.update({
    id: '/cadastros/servicos',
    path: '/cadastros/servicos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosProdutosRoute =
  AuthenticatedCadastrosProdutosRouteImport.update({
    id: '/cadastros/produtos',
    path: '/cadastros/produtos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosEquipesRoute =
  AuthenticatedCadastrosEquipesRouteImport.update({
    id: '/cadastros/equipes',
    path: '/cadastros/equipes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosEpisRoute =
  AuthenticatedCadastrosEpisRouteImport.update({
    id: '/cadastros/epis',
    path: '/cadastros/epis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosCategoriasFinanceirasRoute =
  AuthenticatedCadastrosCategoriasFinanceirasRouteImport.update({
    id: '/cadastros/categorias-financeiras',
    path: '/cadastros/categorias-financeiras',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBiOperacionalRoute =
  AuthenticatedBiOperacionalRouteImport.update({
    id: '/operacional',
    path: '/operacional',
    getParentRoute: () => AuthenticatedBiRoute,
  } as any)
const AuthenticatedBiFinanceiroRoute =
  AuthenticatedBiFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedBiRoute,
  } as any)
const AuthenticatedBiEstoqueRoute = AuthenticatedBiEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedBiRoute,
} as any)
const AuthenticatedBiComercialRoute =
  AuthenticatedBiComercialRouteImport.update({
    id: '/comercial',
    path: '/comercial',
    getParentRoute: () => AuthenticatedBiRoute,
  } as any)
const AuthenticatedFinanceiroReceberIdRoute =
  AuthenticatedFinanceiroReceberIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFinanceiroReceberRoute,
  } as any)
const AuthenticatedFinanceiroPagarIdRoute =
  AuthenticatedFinanceiroPagarIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFinanceiroPagarRoute,
  } as any)
const AuthenticatedFinanceiroLancamentoNovoRoute =
  AuthenticatedFinanceiroLancamentoNovoRouteImport.update({
    id: '/financeiro/lancamento/novo',
    path: '/financeiro/lancamento/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/bi': typeof AuthenticatedBiRouteWithChildren
  '/compliance': typeof AuthenticatedComplianceRouteWithChildren
  '/leads': typeof AuthenticatedLeadsRoute
  '/ces/$token': typeof CesTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/os': typeof PortalOsRoute
  '/portal/propostas': typeof PortalPropostasRoute
  '/portal/': typeof PortalIndexRoute
  '/bi/comercial': typeof AuthenticatedBiComercialRoute
  '/bi/estoque': typeof AuthenticatedBiEstoqueRoute
  '/bi/financeiro': typeof AuthenticatedBiFinanceiroRoute
  '/bi/operacional': typeof AuthenticatedBiOperacionalRoute
  '/cadastros/categorias-financeiras': typeof AuthenticatedCadastrosCategoriasFinanceirasRoute
  '/cadastros/epis': typeof AuthenticatedCadastrosEpisRoute
  '/cadastros/equipes': typeof AuthenticatedCadastrosEquipesRoute
  '/cadastros/produtos': typeof AuthenticatedCadastrosProdutosRoute
  '/cadastros/servicos': typeof AuthenticatedCadastrosServicosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/compliance/certificados': typeof AuthenticatedComplianceCertificadosRoute
  '/compliance/embalagens': typeof AuthenticatedComplianceEmbalagensRoute
  '/compliance/epis': typeof AuthenticatedComplianceEpisRoute
  '/compliance/livro-aplicacoes': typeof AuthenticatedComplianceLivroAplicacoesRoute
  '/compliance/produtos-regulatorio': typeof AuthenticatedComplianceProdutosRegulatorioRoute
  '/compliance/rt': typeof AuthenticatedComplianceRtRoute
  '/diagnosticos/novo': typeof AuthenticatedDiagnosticosNovoRoute
  '/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRouteWithChildren
  '/financeiro/receber': typeof AuthenticatedFinanceiroReceberRouteWithChildren
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/propostas/$id': typeof AuthenticatedPropostasIdRoute
  '/bi/': typeof AuthenticatedBiIndexRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/os/': typeof AuthenticatedOsIndexRoute
  '/propostas/': typeof AuthenticatedPropostasIndexRoute
  '/financeiro/lancamento/novo': typeof AuthenticatedFinanceiroLancamentoNovoRoute
  '/financeiro/pagar/$id': typeof AuthenticatedFinanceiroPagarIdRoute
  '/financeiro/receber/$id': typeof AuthenticatedFinanceiroReceberIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/ces/$token': typeof CesTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/os': typeof PortalOsRoute
  '/portal/propostas': typeof PortalPropostasRoute
  '/': typeof AuthenticatedIndexRoute
  '/portal': typeof PortalIndexRoute
  '/bi/comercial': typeof AuthenticatedBiComercialRoute
  '/bi/estoque': typeof AuthenticatedBiEstoqueRoute
  '/bi/financeiro': typeof AuthenticatedBiFinanceiroRoute
  '/bi/operacional': typeof AuthenticatedBiOperacionalRoute
  '/cadastros/categorias-financeiras': typeof AuthenticatedCadastrosCategoriasFinanceirasRoute
  '/cadastros/epis': typeof AuthenticatedCadastrosEpisRoute
  '/cadastros/equipes': typeof AuthenticatedCadastrosEquipesRoute
  '/cadastros/produtos': typeof AuthenticatedCadastrosProdutosRoute
  '/cadastros/servicos': typeof AuthenticatedCadastrosServicosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/compliance/certificados': typeof AuthenticatedComplianceCertificadosRoute
  '/compliance/embalagens': typeof AuthenticatedComplianceEmbalagensRoute
  '/compliance/epis': typeof AuthenticatedComplianceEpisRoute
  '/compliance/livro-aplicacoes': typeof AuthenticatedComplianceLivroAplicacoesRoute
  '/compliance/produtos-regulatorio': typeof AuthenticatedComplianceProdutosRegulatorioRoute
  '/compliance/rt': typeof AuthenticatedComplianceRtRoute
  '/diagnosticos/novo': typeof AuthenticatedDiagnosticosNovoRoute
  '/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRouteWithChildren
  '/financeiro/receber': typeof AuthenticatedFinanceiroReceberRouteWithChildren
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/propostas/$id': typeof AuthenticatedPropostasIdRoute
  '/bi': typeof AuthenticatedBiIndexRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/compliance': typeof AuthenticatedComplianceIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/os': typeof AuthenticatedOsIndexRoute
  '/propostas': typeof AuthenticatedPropostasIndexRoute
  '/financeiro/lancamento/novo': typeof AuthenticatedFinanceiroLancamentoNovoRoute
  '/financeiro/pagar/$id': typeof AuthenticatedFinanceiroPagarIdRoute
  '/financeiro/receber/$id': typeof AuthenticatedFinanceiroReceberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/_authenticated/bi': typeof AuthenticatedBiRouteWithChildren
  '/_authenticated/compliance': typeof AuthenticatedComplianceRouteWithChildren
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/ces/$token': typeof CesTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/os': typeof PortalOsRoute
  '/portal/propostas': typeof PortalPropostasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/bi/comercial': typeof AuthenticatedBiComercialRoute
  '/_authenticated/bi/estoque': typeof AuthenticatedBiEstoqueRoute
  '/_authenticated/bi/financeiro': typeof AuthenticatedBiFinanceiroRoute
  '/_authenticated/bi/operacional': typeof AuthenticatedBiOperacionalRoute
  '/_authenticated/cadastros/categorias-financeiras': typeof AuthenticatedCadastrosCategoriasFinanceirasRoute
  '/_authenticated/cadastros/epis': typeof AuthenticatedCadastrosEpisRoute
  '/_authenticated/cadastros/equipes': typeof AuthenticatedCadastrosEquipesRoute
  '/_authenticated/cadastros/produtos': typeof AuthenticatedCadastrosProdutosRoute
  '/_authenticated/cadastros/servicos': typeof AuthenticatedCadastrosServicosRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/compliance/certificados': typeof AuthenticatedComplianceCertificadosRoute
  '/_authenticated/compliance/embalagens': typeof AuthenticatedComplianceEmbalagensRoute
  '/_authenticated/compliance/epis': typeof AuthenticatedComplianceEpisRoute
  '/_authenticated/compliance/livro-aplicacoes': typeof AuthenticatedComplianceLivroAplicacoesRoute
  '/_authenticated/compliance/produtos-regulatorio': typeof AuthenticatedComplianceProdutosRegulatorioRoute
  '/_authenticated/compliance/rt': typeof AuthenticatedComplianceRtRoute
  '/_authenticated/diagnosticos/novo': typeof AuthenticatedDiagnosticosNovoRoute
  '/_authenticated/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRouteWithChildren
  '/_authenticated/financeiro/receber': typeof AuthenticatedFinanceiroReceberRouteWithChildren
  '/_authenticated/os/$id': typeof AuthenticatedOsIdRoute
  '/_authenticated/propostas/$id': typeof AuthenticatedPropostasIdRoute
  '/_authenticated/bi/': typeof AuthenticatedBiIndexRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/os/': typeof AuthenticatedOsIndexRoute
  '/_authenticated/propostas/': typeof AuthenticatedPropostasIndexRoute
  '/_authenticated/financeiro/lancamento/novo': typeof AuthenticatedFinanceiroLancamentoNovoRoute
  '/_authenticated/financeiro/pagar/$id': typeof AuthenticatedFinanceiroPagarIdRoute
  '/_authenticated/financeiro/receber/$id': typeof AuthenticatedFinanceiroReceberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/bi'
    | '/compliance'
    | '/leads'
    | '/ces/$token'
    | '/invite/$token'
    | '/portal/documentos'
    | '/portal/financeiro'
    | '/portal/os'
    | '/portal/propostas'
    | '/portal/'
    | '/bi/comercial'
    | '/bi/estoque'
    | '/bi/financeiro'
    | '/bi/operacional'
    | '/cadastros/categorias-financeiras'
    | '/cadastros/epis'
    | '/cadastros/equipes'
    | '/cadastros/produtos'
    | '/cadastros/servicos'
    | '/clientes/$id'
    | '/compliance/certificados'
    | '/compliance/embalagens'
    | '/compliance/epis'
    | '/compliance/livro-aplicacoes'
    | '/compliance/produtos-regulatorio'
    | '/compliance/rt'
    | '/diagnosticos/novo'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/os/$id'
    | '/propostas/$id'
    | '/bi/'
    | '/clientes/'
    | '/compliance/'
    | '/financeiro/'
    | '/os/'
    | '/propostas/'
    | '/financeiro/lancamento/novo'
    | '/financeiro/pagar/$id'
    | '/financeiro/receber/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/leads'
    | '/ces/$token'
    | '/invite/$token'
    | '/portal/documentos'
    | '/portal/financeiro'
    | '/portal/os'
    | '/portal/propostas'
    | '/'
    | '/portal'
    | '/bi/comercial'
    | '/bi/estoque'
    | '/bi/financeiro'
    | '/bi/operacional'
    | '/cadastros/categorias-financeiras'
    | '/cadastros/epis'
    | '/cadastros/equipes'
    | '/cadastros/produtos'
    | '/cadastros/servicos'
    | '/clientes/$id'
    | '/compliance/certificados'
    | '/compliance/embalagens'
    | '/compliance/epis'
    | '/compliance/livro-aplicacoes'
    | '/compliance/produtos-regulatorio'
    | '/compliance/rt'
    | '/diagnosticos/novo'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/os/$id'
    | '/propostas/$id'
    | '/bi'
    | '/clientes'
    | '/compliance'
    | '/financeiro'
    | '/os'
    | '/propostas'
    | '/financeiro/lancamento/novo'
    | '/financeiro/pagar/$id'
    | '/financeiro/receber/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/portal'
    | '/_authenticated/bi'
    | '/_authenticated/compliance'
    | '/_authenticated/leads'
    | '/ces/$token'
    | '/invite/$token'
    | '/portal/documentos'
    | '/portal/financeiro'
    | '/portal/os'
    | '/portal/propostas'
    | '/_authenticated/'
    | '/portal/'
    | '/_authenticated/bi/comercial'
    | '/_authenticated/bi/estoque'
    | '/_authenticated/bi/financeiro'
    | '/_authenticated/bi/operacional'
    | '/_authenticated/cadastros/categorias-financeiras'
    | '/_authenticated/cadastros/epis'
    | '/_authenticated/cadastros/equipes'
    | '/_authenticated/cadastros/produtos'
    | '/_authenticated/cadastros/servicos'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/compliance/certificados'
    | '/_authenticated/compliance/embalagens'
    | '/_authenticated/compliance/epis'
    | '/_authenticated/compliance/livro-aplicacoes'
    | '/_authenticated/compliance/produtos-regulatorio'
    | '/_authenticated/compliance/rt'
    | '/_authenticated/diagnosticos/novo'
    | '/_authenticated/financeiro/pagar'
    | '/_authenticated/financeiro/receber'
    | '/_authenticated/os/$id'
    | '/_authenticated/propostas/$id'
    | '/_authenticated/bi/'
    | '/_authenticated/clientes/'
    | '/_authenticated/compliance/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/os/'
    | '/_authenticated/propostas/'
    | '/_authenticated/financeiro/lancamento/novo'
    | '/_authenticated/financeiro/pagar/$id'
    | '/_authenticated/financeiro/receber/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRouteWithChildren
  CesTokenRoute: typeof CesTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/propostas': {
      id: '/portal/propostas'
      path: '/propostas'
      fullPath: '/portal/propostas'
      preLoaderRoute: typeof PortalPropostasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/os': {
      id: '/portal/os'
      path: '/os'
      fullPath: '/portal/os'
      preLoaderRoute: typeof PortalOsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/financeiro': {
      id: '/portal/financeiro'
      path: '/financeiro'
      fullPath: '/portal/financeiro'
      preLoaderRoute: typeof PortalFinanceiroRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documentos': {
      id: '/portal/documentos'
      path: '/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof PortalDocumentosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ces/$token': {
      id: '/ces/$token'
      path: '/ces/$token'
      fullPath: '/ces/$token'
      preLoaderRoute: typeof CesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bi': {
      id: '/_authenticated/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedBiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/propostas/': {
      id: '/_authenticated/propostas/'
      path: '/propostas'
      fullPath: '/propostas/'
      preLoaderRoute: typeof AuthenticatedPropostasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/os/': {
      id: '/_authenticated/os/'
      path: '/os'
      fullPath: '/os/'
      preLoaderRoute: typeof AuthenticatedOsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/': {
      id: '/_authenticated/compliance/'
      path: '/'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AuthenticatedComplianceIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bi/': {
      id: '/_authenticated/bi/'
      path: '/'
      fullPath: '/bi/'
      preLoaderRoute: typeof AuthenticatedBiIndexRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/propostas/$id': {
      id: '/_authenticated/propostas/$id'
      path: '/propostas/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof AuthenticatedPropostasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/os/$id': {
      id: '/_authenticated/os/$id'
      path: '/os/$id'
      fullPath: '/os/$id'
      preLoaderRoute: typeof AuthenticatedOsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/receber': {
      id: '/_authenticated/financeiro/receber'
      path: '/financeiro/receber'
      fullPath: '/financeiro/receber'
      preLoaderRoute: typeof AuthenticatedFinanceiroReceberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/pagar': {
      id: '/_authenticated/financeiro/pagar'
      path: '/financeiro/pagar'
      fullPath: '/financeiro/pagar'
      preLoaderRoute: typeof AuthenticatedFinanceiroPagarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnosticos/novo': {
      id: '/_authenticated/diagnosticos/novo'
      path: '/diagnosticos/novo'
      fullPath: '/diagnosticos/novo'
      preLoaderRoute: typeof AuthenticatedDiagnosticosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/rt': {
      id: '/_authenticated/compliance/rt'
      path: '/rt'
      fullPath: '/compliance/rt'
      preLoaderRoute: typeof AuthenticatedComplianceRtRouteImport
      parentRoute: typeof AuthenticatedComplianceRoute
    }
    '/_authenticated/compliance/produtos-regulatorio': {
      id: '/_authenticated/compliance/produtos-regulatorio'
      path: '/produtos-regulatorio'
      fullPath: '/compliance/produtos-regulatorio'
      preLoaderRoute: typeof AuthenticatedComplianceProdutosRegulatorioRouteImport
      parentRoute: typeof AuthenticatedComplianceRoute
    }
    '/_authenticated/compliance/livro-aplicacoes': {
      id: '/_authenticated/compliance/livro-aplicacoes'
      path: '/livro-aplicacoes'
      fullPath: '/compliance/livro-aplicacoes'
      preLoaderRoute: typeof AuthenticatedComplianceLivroAplicacoesRouteImport
      parentRoute: typeof AuthenticatedComplianceRoute
    }
    '/_authenticated/compliance/epis': {
      id: '/_authenticated/compliance/epis'
      path: '/epis'
      fullPath: '/compliance/epis'
      preLoaderRoute: typeof AuthenticatedComplianceEpisRouteImport
      parentRoute: typeof AuthenticatedComplianceRoute
    }
    '/_authenticated/compliance/embalagens': {
      id: '/_authenticated/compliance/embalagens'
      path: '/embalagens'
      fullPath: '/compliance/embalagens'
      preLoaderRoute: typeof AuthenticatedComplianceEmbalagensRouteImport
      parentRoute: typeof AuthenticatedComplianceRoute
    }
    '/_authenticated/compliance/certificados': {
      id: '/_authenticated/compliance/certificados'
      path: '/certificados'
      fullPath: '/compliance/certificados'
      preLoaderRoute: typeof AuthenticatedComplianceCertificadosRouteImport
      parentRoute: typeof AuthenticatedComplianceRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/servicos': {
      id: '/_authenticated/cadastros/servicos'
      path: '/cadastros/servicos'
      fullPath: '/cadastros/servicos'
      preLoaderRoute: typeof AuthenticatedCadastrosServicosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/produtos': {
      id: '/_authenticated/cadastros/produtos'
      path: '/cadastros/produtos'
      fullPath: '/cadastros/produtos'
      preLoaderRoute: typeof AuthenticatedCadastrosProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/equipes': {
      id: '/_authenticated/cadastros/equipes'
      path: '/cadastros/equipes'
      fullPath: '/cadastros/equipes'
      preLoaderRoute: typeof AuthenticatedCadastrosEquipesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/epis': {
      id: '/_authenticated/cadastros/epis'
      path: '/cadastros/epis'
      fullPath: '/cadastros/epis'
      preLoaderRoute: typeof AuthenticatedCadastrosEpisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/categorias-financeiras': {
      id: '/_authenticated/cadastros/categorias-financeiras'
      path: '/cadastros/categorias-financeiras'
      fullPath: '/cadastros/categorias-financeiras'
      preLoaderRoute: typeof AuthenticatedCadastrosCategoriasFinanceirasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bi/operacional': {
      id: '/_authenticated/bi/operacional'
      path: '/operacional'
      fullPath: '/bi/operacional'
      preLoaderRoute: typeof AuthenticatedBiOperacionalRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/bi/financeiro': {
      id: '/_authenticated/bi/financeiro'
      path: '/financeiro'
      fullPath: '/bi/financeiro'
      preLoaderRoute: typeof AuthenticatedBiFinanceiroRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/bi/estoque': {
      id: '/_authenticated/bi/estoque'
      path: '/estoque'
      fullPath: '/bi/estoque'
      preLoaderRoute: typeof AuthenticatedBiEstoqueRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/bi/comercial': {
      id: '/_authenticated/bi/comercial'
      path: '/comercial'
      fullPath: '/bi/comercial'
      preLoaderRoute: typeof AuthenticatedBiComercialRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/financeiro/receber/$id': {
      id: '/_authenticated/financeiro/receber/$id'
      path: '/$id'
      fullPath: '/financeiro/receber/$id'
      preLoaderRoute: typeof AuthenticatedFinanceiroReceberIdRouteImport
      parentRoute: typeof AuthenticatedFinanceiroReceberRoute
    }
    '/_authenticated/financeiro/pagar/$id': {
      id: '/_authenticated/financeiro/pagar/$id'
      path: '/$id'
      fullPath: '/financeiro/pagar/$id'
      preLoaderRoute: typeof AuthenticatedFinanceiroPagarIdRouteImport
      parentRoute: typeof AuthenticatedFinanceiroPagarRoute
    }
    '/_authenticated/financeiro/lancamento/novo': {
      id: '/_authenticated/financeiro/lancamento/novo'
      path: '/financeiro/lancamento/novo'
      fullPath: '/financeiro/lancamento/novo'
      preLoaderRoute: typeof AuthenticatedFinanceiroLancamentoNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedBiRouteChildren {
  AuthenticatedBiComercialRoute: typeof AuthenticatedBiComercialRoute
  AuthenticatedBiEstoqueRoute: typeof AuthenticatedBiEstoqueRoute
  AuthenticatedBiFinanceiroRoute: typeof AuthenticatedBiFinanceiroRoute
  AuthenticatedBiOperacionalRoute: typeof AuthenticatedBiOperacionalRoute
  AuthenticatedBiIndexRoute: typeof AuthenticatedBiIndexRoute
}

const AuthenticatedBiRouteChildren: AuthenticatedBiRouteChildren = {
  AuthenticatedBiComercialRoute: AuthenticatedBiComercialRoute,
  AuthenticatedBiEstoqueRoute: AuthenticatedBiEstoqueRoute,
  AuthenticatedBiFinanceiroRoute: AuthenticatedBiFinanceiroRoute,
  AuthenticatedBiOperacionalRoute: AuthenticatedBiOperacionalRoute,
  AuthenticatedBiIndexRoute: AuthenticatedBiIndexRoute,
}

const AuthenticatedBiRouteWithChildren = AuthenticatedBiRoute._addFileChildren(
  AuthenticatedBiRouteChildren,
)

interface AuthenticatedComplianceRouteChildren {
  AuthenticatedComplianceCertificadosRoute: typeof AuthenticatedComplianceCertificadosRoute
  AuthenticatedComplianceEmbalagensRoute: typeof AuthenticatedComplianceEmbalagensRoute
  AuthenticatedComplianceEpisRoute: typeof AuthenticatedComplianceEpisRoute
  AuthenticatedComplianceLivroAplicacoesRoute: typeof AuthenticatedComplianceLivroAplicacoesRoute
  AuthenticatedComplianceProdutosRegulatorioRoute: typeof AuthenticatedComplianceProdutosRegulatorioRoute
  AuthenticatedComplianceRtRoute: typeof AuthenticatedComplianceRtRoute
  AuthenticatedComplianceIndexRoute: typeof AuthenticatedComplianceIndexRoute
}

const AuthenticatedComplianceRouteChildren: AuthenticatedComplianceRouteChildren =
  {
    AuthenticatedComplianceCertificadosRoute:
      AuthenticatedComplianceCertificadosRoute,
    AuthenticatedComplianceEmbalagensRoute:
      AuthenticatedComplianceEmbalagensRoute,
    AuthenticatedComplianceEpisRoute: AuthenticatedComplianceEpisRoute,
    AuthenticatedComplianceLivroAplicacoesRoute:
      AuthenticatedComplianceLivroAplicacoesRoute,
    AuthenticatedComplianceProdutosRegulatorioRoute:
      AuthenticatedComplianceProdutosRegulatorioRoute,
    AuthenticatedComplianceRtRoute: AuthenticatedComplianceRtRoute,
    AuthenticatedComplianceIndexRoute: AuthenticatedComplianceIndexRoute,
  }

const AuthenticatedComplianceRouteWithChildren =
  AuthenticatedComplianceRoute._addFileChildren(
    AuthenticatedComplianceRouteChildren,
  )

interface AuthenticatedFinanceiroPagarRouteChildren {
  AuthenticatedFinanceiroPagarIdRoute: typeof AuthenticatedFinanceiroPagarIdRoute
}

const AuthenticatedFinanceiroPagarRouteChildren: AuthenticatedFinanceiroPagarRouteChildren =
  {
    AuthenticatedFinanceiroPagarIdRoute: AuthenticatedFinanceiroPagarIdRoute,
  }

const AuthenticatedFinanceiroPagarRouteWithChildren =
  AuthenticatedFinanceiroPagarRoute._addFileChildren(
    AuthenticatedFinanceiroPagarRouteChildren,
  )

interface AuthenticatedFinanceiroReceberRouteChildren {
  AuthenticatedFinanceiroReceberIdRoute: typeof AuthenticatedFinanceiroReceberIdRoute
}

const AuthenticatedFinanceiroReceberRouteChildren: AuthenticatedFinanceiroReceberRouteChildren =
  {
    AuthenticatedFinanceiroReceberIdRoute:
      AuthenticatedFinanceiroReceberIdRoute,
  }

const AuthenticatedFinanceiroReceberRouteWithChildren =
  AuthenticatedFinanceiroReceberRoute._addFileChildren(
    AuthenticatedFinanceiroReceberRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBiRoute: typeof AuthenticatedBiRouteWithChildren
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRouteWithChildren
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCadastrosCategoriasFinanceirasRoute: typeof AuthenticatedCadastrosCategoriasFinanceirasRoute
  AuthenticatedCadastrosEpisRoute: typeof AuthenticatedCadastrosEpisRoute
  AuthenticatedCadastrosEquipesRoute: typeof AuthenticatedCadastrosEquipesRoute
  AuthenticatedCadastrosProdutosRoute: typeof AuthenticatedCadastrosProdutosRoute
  AuthenticatedCadastrosServicosRoute: typeof AuthenticatedCadastrosServicosRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedDiagnosticosNovoRoute: typeof AuthenticatedDiagnosticosNovoRoute
  AuthenticatedFinanceiroPagarRoute: typeof AuthenticatedFinanceiroPagarRouteWithChildren
  AuthenticatedFinanceiroReceberRoute: typeof AuthenticatedFinanceiroReceberRouteWithChildren
  AuthenticatedOsIdRoute: typeof AuthenticatedOsIdRoute
  AuthenticatedPropostasIdRoute: typeof AuthenticatedPropostasIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
  AuthenticatedOsIndexRoute: typeof AuthenticatedOsIndexRoute
  AuthenticatedPropostasIndexRoute: typeof AuthenticatedPropostasIndexRoute
  AuthenticatedFinanceiroLancamentoNovoRoute: typeof AuthenticatedFinanceiroLancamentoNovoRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBiRoute: AuthenticatedBiRouteWithChildren,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRouteWithChildren,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCadastrosCategoriasFinanceirasRoute:
    AuthenticatedCadastrosCategoriasFinanceirasRoute,
  AuthenticatedCadastrosEpisRoute: AuthenticatedCadastrosEpisRoute,
  AuthenticatedCadastrosEquipesRoute: AuthenticatedCadastrosEquipesRoute,
  AuthenticatedCadastrosProdutosRoute: AuthenticatedCadastrosProdutosRoute,
  AuthenticatedCadastrosServicosRoute: AuthenticatedCadastrosServicosRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedDiagnosticosNovoRoute: AuthenticatedDiagnosticosNovoRoute,
  AuthenticatedFinanceiroPagarRoute:
    AuthenticatedFinanceiroPagarRouteWithChildren,
  AuthenticatedFinanceiroReceberRoute:
    AuthenticatedFinanceiroReceberRouteWithChildren,
  AuthenticatedOsIdRoute: AuthenticatedOsIdRoute,
  AuthenticatedPropostasIdRoute: AuthenticatedPropostasIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  AuthenticatedOsIndexRoute: AuthenticatedOsIndexRoute,
  AuthenticatedPropostasIndexRoute: AuthenticatedPropostasIndexRoute,
  AuthenticatedFinanceiroLancamentoNovoRoute:
    AuthenticatedFinanceiroLancamentoNovoRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalRouteChildren {
  PortalDocumentosRoute: typeof PortalDocumentosRoute
  PortalFinanceiroRoute: typeof PortalFinanceiroRoute
  PortalOsRoute: typeof PortalOsRoute
  PortalPropostasRoute: typeof PortalPropostasRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDocumentosRoute: PortalDocumentosRoute,
  PortalFinanceiroRoute: PortalFinanceiroRoute,
  PortalOsRoute: PortalOsRoute,
  PortalPropostasRoute: PortalPropostasRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRouteWithChildren,
  CesTokenRoute: CesTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
